app = "sampleapptest-dev"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# [deploy]
#   release_command = "python /app/manage.py migrate"

[build]
  dockerfile = "Dockerfile"
  build-target = "runtime"

[env]
  DJANGO_SECRET_KEY="!!! CHANGE ME !!!"
  PORT = "8080"
  DJANGO_ALLOWED_HOSTS="*"
  DJANGO_AWS_ACCESS_KEY_ID=""
  DJANGO_AWS_SECRET_ACCESS_KEY=""
  DJANGO_AWS_STORAGE_BUCKET_NAME=""
  DJANGO_AWS_S3_ENDPOINT_URL=""
  SENTRY_DSN=""
  REDIS_URL=""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/sampleapp/static"
  url_prefix = "/static/"